import { GoogleGenerativeAI } from '@google/generative-ai';
import type { PosterGenerationParams, PosterType } from '@/types/poster';

/**
 * Generate a world-class AI prompt for poster creation
 * Handles both festive and regular advertisements with premium aesthetic
 */
const generateAIPrompt = (
    brandName: string,
    description: string,
    productUrl: string | undefined,
    imageCount: number,
    hasLogo: boolean,
    posterType: PosterType,
    festivalName: string | undefined,
    contactPhone: string | undefined,
    website: string | undefined,
    address: string | undefined,
    aspectRatio: string
): string => {
  // Base aesthetic for "World's Greatest Ad Creator" style
  const stylePrefix = "A world-class, high-end commercial advertisement poster with a premium aesthetic. Professional studio lighting, cinematic composition, and 8k resolution.";
  
  // Handling the core content
  const coreContent = `The advertisement is for a brand called '${brandName}', which focuses on: ${description}.`;
  
  // Festive vs. Regular logic
  const context = posterType === 'Festival' && festivalName
    ? `The theme is a grand celebration of ${festivalName}. Incorporate elegant festive elements, vibrant colors associated with the occasion, and a joyful, prestigious atmosphere.`
    : "The theme is modern, minimalist, and corporate. Focus on sleek lines, sophisticated color palettes, and a clear 'call to action' vibe.";

  // Handling product and logo integration
  const mediaInstruction = imageCount > 0 && hasLogo
    ? "Highlight the provided product photo as the focal point and seamlessly integrate the brand logo in a prominent but balanced position."
    : imageCount > 0
    ? "Highlight the provided product photo as the central focal point with professional composition."
    : hasLogo
    ? "Create a strong visual presence for the provided brand logo and develop a photorealistic representation of the product based on the brand description."
    : "Generate a photorealistic representation of the product that embodies the brand essence and description.";

  // Handling contact details for text rendering
  const contactInfo = (contactPhone || website || address)
    ? `Visually integrate the following contact details in a clean, professional font placed in a footer or corner: ${[contactPhone, website, address].filter(Boolean).join(' | ')}.`
    : "";

  return `${stylePrefix} ${coreContent} ${context} ${mediaInstruction} ${contactInfo} Aspect ratio: ${aspectRatio}. Ensure the composition looks like a masterpiece from a top-tier global design agency. The final output should have premium realism with no artificial or "uncanny valley" appearance.`;
};

export const generatePoster = async (params: PosterGenerationParams): Promise<string> => {
  const {
      brandName,
      description,
      productImages,
      productUrl,
      brandLogo,
      aspectRatio,
      posterType,
      festivalName,
      contactPhone,
      website,
      address,
      baseImage
  } = params;

  if (!process.env.GOOGLE_AI_API_KEY) {
    throw new Error("GOOGLE_AI_API_KEY environment variable not set");
  }

  const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY);

  // Generate the world-class prompt
  const prompt = generateAIPrompt(
      brandName,
      description,
      productUrl,
      productImages.length,
      !!brandLogo,
      posterType,
      festivalName,
      contactPhone,
      website,
      address,
      aspectRatio
  );

  try {
    console.log('Calling Google Gemini API for image generation');
    
    // Get the Imagen model from the GenAI client
    const model = genAI.getGenerativeModel({ model: 'models/imagen-3.0-generate-002' });

    // Call the generateImages method
    const result = await model.generateImages({
      prompt: prompt,
      aspectRatio: aspectRatio || '3:4',
    });

    console.log('Gemini image generation response received');

    // SAFE VALIDATION: Check if response exists
    if (!result) {
      throw new Error('Empty response from API');
    }

    // SAFE VALIDATION: Check if images were generated
    if (!result.images || result.images.length === 0) {
      console.error('No images generated by the API');
      throw new Error('AI API Error: No image was generated by the API. The prompt may have been blocked by safety filters.');
    }

    const image = result.images[0];

    // SAFE VALIDATION: Ensure image data exists
    if (!image) {
      throw new Error('Generated image is empty');
    }

    // Handle different possible image data formats
    let imageBase64: string;
    if (typeof image === 'string') {
      imageBase64 = image;
    } else if (typeof image === 'object' && 'data' in image) {
      imageBase64 = (image as any).data;
    } else if (typeof image === 'object' && 'base64' in image) {
      imageBase64 = (image as any).base64;
    } else {
      throw new Error('Unable to extract image data from response');
    }

    if (!imageBase64 || imageBase64.trim() === '') {
      throw new Error('Generated image data is empty');
    }

    // Return the base64 image data with proper data URI format
    const mimeType = 'image/jpeg';
    return `data:${mimeType};base64,${imageBase64}`;
  } catch (apiError) {
    console.error('Google Gemini API Error:', apiError);
    const errorMessage = apiError instanceof Error ? apiError.message : 'Unknown API error';
    throw new Error(`AI API Error: ${errorMessage}`);
  }
};