// hApItech Production Suite geminiService
import { GoogleGenAI } from '@google/genai';

interface PosterSuiteParams {
  productImage: File;
  brandLogo?: File | null;
  industry: string;
  description: string;
  headline: string;
  tagline: string;
}

export async function generateProductionPoster({ productImage, brandLogo, industry, description, headline, tagline }: PosterSuiteParams): Promise<string> {
  if (!process.env.API_KEY) throw new Error('API_KEY not set');
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  // Convert files to base64
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = error => reject(error);
    });
  };
  const productImageBase64 = await fileToBase64(productImage);
  const brandLogoBase64 = brandLogo ? await fileToBase64(brandLogo) : null;

  // Prompt engineering
  const prompt = `
You are a world-class commercial design director at a luxury digital studio. Create a cinematic, magazine-style poster for a premium brand.

STRICT REQUIREMENTS:
- Use the provided product image as the visual centerpiece. Do NOT distort or obscure it.
- Render the following text LITERALLY, character-perfect, with NO rewriting or translation:
  - Headline: "${headline}"
  - Tagline: "${tagline}"
- Use the provided brand logo (if any) as a supporting element.
- Industry: ${industry}
- Description: ${description}
- The design must be minimal, editorial, and cinematic. Use glassmorphism, soft shadows, and a premium color palette.
- Typography: Headline and tagline must be visually distinct, using high-end editorial style.
- Output must be high-resolution, suitable for print and digital, and aspect ratio 3:4.
- No watermarks, no extra branding, no AI signatures.
- Multi-language safe (English, Hindi, Gujarati, etc.)
`;

  const parts: any[] = [];
  // Add product image
  parts.push({
    inlineData: {
      data: productImageBase64.replace(/^data:image\/[a-z]+;base64,/, ''),
      mimeType: 'image/jpeg',
    }
  });
  // Add brand logo if present
  if (brandLogoBase64) {
    parts.push({
      inlineData: {
        data: brandLogoBase64.replace(/^data:image\/[a-z]+;base64,/, ''),
        mimeType: 'image/png',
      }
    });
  }
  parts.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: 'models/gemini-2.0-flash',
    contents: [{ role: 'user', parts }],
    safetySettings: [
      { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_ONLY_HIGH' },
      { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_ONLY_HIGH' },
      { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_ONLY_HIGH' },
      { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_ONLY_HIGH' },
    ],
  } as any);

  if (!response.candidates || response.candidates.length === 0) {
    throw new Error('No candidates in API response');
  }
  const content = response.candidates[0].content;
  if (!content || !content.parts || content.parts.length === 0) {
    throw new Error('No content in API response');
  }
  const firstPart = content.parts[0];
  if ('inlineData' in firstPart && firstPart.inlineData) {
    const base64ImageBytes = firstPart.inlineData.data;
    if (!base64ImageBytes) throw new Error('Image data is empty');
    const mimeType = firstPart.inlineData.mimeType || 'image/jpeg';
    return `data:${mimeType};base64,${base64ImageBytes}`;
  }
  throw new Error('No image was generated by the API');
}