import { GoogleGenAI } from '@google/genai';
import type { PosterGenerationParams, PosterType } from '@/types/poster';

/**
 * Generate a world-class AI prompt for poster creation
 * Handles both festive and regular advertisements with premium aesthetic
 */
const generateAIPrompt = (
    brandName: string,
    description: string,
    productUrl: string | undefined,
    imageCount: number,
    hasLogo: boolean,
    posterType: PosterType,
    festivalName: string | undefined,
    contactPhone: string | undefined,
    website: string | undefined,
    address: string | undefined,
    aspectRatio: string
): string => {
  // Base aesthetic for "World's Greatest Ad Creator" style
  const stylePrefix = "A world-class, high-end commercial advertisement poster with a premium aesthetic. Professional studio lighting, cinematic composition, and 8k resolution.";
  
  // Handling the core content
  const coreContent = `The advertisement is for a brand called '${brandName}', which focuses on: ${description}.`;
  
  // Festive vs. Regular logic
  const context = posterType === 'Festival' && festivalName
    ? `The theme is a grand celebration of ${festivalName}. Incorporate elegant festive elements, vibrant colors associated with the occasion, and a joyful, prestigious atmosphere.`
    : "The theme is modern, minimalist, and corporate. Focus on sleek lines, sophisticated color palettes, and a clear 'call to action' vibe.";

  // Handling product and logo integration
  const mediaInstruction = imageCount > 0 && hasLogo
    ? "Highlight the provided product photo as the focal point and seamlessly integrate the brand logo in a prominent but balanced position."
    : imageCount > 0
    ? "Highlight the provided product photo as the central focal point with professional composition."
    : hasLogo
    ? "Create a strong visual presence for the provided brand logo and develop a photorealistic representation of the product based on the brand description."
    : "Generate a photorealistic representation of the product that embodies the brand essence and description.";

  // Handling contact details for text rendering
  const contactInfo = (contactPhone || website || address)
    ? `Visually integrate the following contact details in a clean, professional font placed in a footer or corner: ${[contactPhone, website, address].filter(Boolean).join(' | ')}.`
    : "";

  return `${stylePrefix} ${coreContent} ${context} ${mediaInstruction} ${contactInfo} Aspect ratio: ${aspectRatio}. Ensure the composition looks like a masterpiece from a top-tier global design agency. The final output should have premium realism with no artificial or "uncanny valley" appearance.`;
};

export const generatePoster = async (params: PosterGenerationParams): Promise<string> => {
  const {
      brandName,
      description,
      productImages,
      productUrl,
      brandLogo,
      aspectRatio,
      posterType,
      festivalName,
      contactPhone,
      website,
      address,
      baseImage
  } = params;

  if (!process.env.GOOGLE_AI_API_KEY) {
    throw new Error("GOOGLE_AI_API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_AI_API_KEY });

  // Generate the world-class prompt
  const prompt = generateAIPrompt(
      brandName,
      description,
      productUrl,
      productImages.length,
      !!brandLogo,
      posterType,
      festivalName,
      contactPhone,
      website,
      address,
      aspectRatio
  );

  try {
    console.log('Calling Google AI API with model gemini-3-pro-image');
    
    // Use generateContent with safety settings for image generation
    const result = await ai.models.generateContent({
      model: 'models/gemini-3-pro-image',
      contents: [{
        role: 'user',
        parts: [{ text: prompt }],
      }],
      // Type assertion needed for safety settings - available at runtime
      safetySettings: [
        {
          category: 'HARM_CATEGORY_HARASSMENT',
          threshold: 'BLOCK_ONLY_HIGH',
        },
        {
          category: 'HARM_CATEGORY_HATE_SPEECH',
          threshold: 'BLOCK_ONLY_HIGH',
        },
        {
          category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
          threshold: 'BLOCK_ONLY_HIGH',
        },
        {
          category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
          threshold: 'BLOCK_ONLY_HIGH',
        },
      ],
    } as any);

    console.log('AI API response received');

    // SAFE VALIDATION: Check if response exists
    if (!result) {
      throw new Error('Empty response from API');
    }

    // SAFE VALIDATION: Check if candidates exist and have content
    if (!result.candidates || result.candidates.length === 0) {
      console.error('No candidates in API response');
      throw new Error('No image was generated by the API. The prompt may have been blocked by safety filters.');
    }

    const content = result.candidates[0].content;

    // SAFE VALIDATION: Check if content exists
    if (!content) {
      throw new Error('No content in candidate response');
    }

    // SAFE VALIDATION: Check if parts exist
    if (!content.parts || content.parts.length === 0) {
      throw new Error('No parts in content');
    }

    // SAFE VALIDATION: Find image data in parts
    const firstPart = content.parts[0];
    
    // Check if first part is valid and contains inline image data
    if (!firstPart) {
      throw new Error('First part is empty');
    }
    
    if ('inlineData' in firstPart && firstPart.inlineData) {
      const base64ImageBytes = firstPart.inlineData.data;
      
      // SAFE VALIDATION: Ensure image data exists
      if (!base64ImageBytes) {
        throw new Error('Image data is empty');
      }
      
      const mimeType = firstPart.inlineData.mimeType || 'image/jpeg';
      return `data:${mimeType};base64,${base64ImageBytes}`;
    }

    // If we reach here, no valid image data was found
    throw new Error('No image was generated by the API');
  } catch (apiError) {
    console.error('Google AI API Error:', apiError);
    const errorMessage = apiError instanceof Error ? apiError.message : 'Unknown API error';
    throw new Error(`AI API Error: ${errorMessage}`);
  }
};